const CREDENTIALS = {
    USER: "system",
    PASSWORD: "Asdf1234$",
    CONNECTSTRING: "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=orcl.mshome.net)))"
}

module.exports = CREDENTIALS;